### ISSUE TITLE
Had a "Unsupported major.minor version 51.0" error at PHPStorm 9 start (OS X 10)

### ISSUE THREAD

**Issue by ronanguilloux** [dryabov/phpregexp#6]
Using brand new stable PHPStorm 9 release (today's build)

``` bash
$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

**Comment by dryabov** [comment]
Hmm, "version 51.0" is Java 7, so I guess that PhpStorm is running using older Java version, but I don't know how to check it.

**Comment by dryabov** [comment]
I've found a comment about set Java version in IDEA, maybe there is a similar issue in PhpStorm: https://github.com/wakatime/jetbrains-wakatime/issues/25#issuecomment-79097268

**Comment by ronanguilloux** [comment]
Good point!

just _pro memoria_:

``` bash
[edit] /Applications/PhpStorm.app/Contents/Info.plist
```

Search for they key/value pair

``` xml
<key>JVMVersion</key>
<string>1.6*,1.7+</string>
```

And change it to

``` xml
<key>JVMVersion</key>
<string>1.8*</string>
```

This will make PhpStorm IDEA start using JRE 1.8.
Source: [Selecting the JDK version the IDE will run under](https://intellij-support.jetbrains.com/hc/en-us/articles/206827547-Selecting-the-JDK-version-the-IDE-will-run-under)
